# Cloudflare Pages configuration for SPA mode
# https://developers.cloudflare.com/pages/configuration/redirects/

[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/_serverFn/*"
  to = "/_serverFn/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/_shell.html"
  status = 200

# Cache headers
[[headers]]
  for = "/_shell.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_app/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
